### ISSUE TITLE
Validation Failed - invalid annotations

### ISSUE THREAD

**Issue by timja** [jenkinsci/github-checks-plugin#20]
I did this commit: https://github.com/timja-org/codingstyle/pull/6/commits/f7793800117788a91cf81402c605faad304ffb43

and in the server log I have:
We probably need to log the annotation as well?
```
org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/timja-org/codingstyle/check-runs {"message":"Validation Failed","errors":[{"resource":"CheckRun","code":"invalid","field":"annotations"}],"documentation_url":"https://docs.github.com/rest/reference/checks#create-a-check-run"}
	at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:493)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:421)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:364)
	at org.kohsuke.github.Requester.fetch(Requester.java:74)
	at org.kohsuke.github.GHCheckRunBuilder.create(GHCheckRunBuilder.java:137)
	at io.jenkins.plugins.checks.github.GitHubChecksPublisher.publish(GitHubChecksPublisher.java:61)
	at io.jenkins.plugins.analysis.core.steps.WarningChecksPublisher.publishChecks(WarningChecksPublisher.java:55)
	at io.jenkins.plugins.analysis.core.steps.IssuesRecorder.publishResult(IssuesRecorder.java:725)
	at io.jenkins.plugins.analysis.core.steps.IssuesRecorder.record(IssuesRecorder.java:651)
	at io.jenkins.plugins.analysis.core.steps.IssuesRecorder.perform(IssuesRecorder.java:617)
	at io.jenkins.plugins.analysis.core.steps.RecordIssuesStep$Execution.run(RecordIssuesStep.java:1024)
	at io.jenkins.plugins.analysis.core.steps.RecordIssuesStep$Execution.run(RecordIssuesStep.java:985)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/timja-org/codingstyle/check-runs
	at org.kohsuke.github.extras.okhttp3.ObsoleteUrlFactory$OkHttpURLConnection.getInputStream(ObsoleteUrlFactory.java:488)
	at org.kohsuke.github.extras.okhttp3.ObsoleteUrlFactory$DelegatingHttpsURLConnection.getInputStream(ObsoleteUrlFactory.java:1201)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.bodyStream(GitHubHttpUrlConnectionClient.java:197)
	at org.kohsuke.github.GitHubResponse$ResponseInfo.getBodyAsString(GitHubResponse.java:321)
	at org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:86)
	at org.kohsuke.github.Requester.lambda$fetch$1(Requester.java:74)
	at org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:462)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:413)
	... 17 more
```

**Comment by timja** [comment]
I added logging and this is the failure:

```
WARNING: Failed Publishing GitHub checks: ChecksDetails{name='SpotBugs', status=COMPLETED, detailsURL='http://localhost:8085/jenkins/job/timja-org/job/codingstyle/job/PR-6/11/', startedAt=null, conclusion=FAILURE, completedAt=null, output=ChecksOutput{title='2 new issues.', summary='## 2 issues in total:
- ### 2 new issues
- ### 0 outstanding issues
- ### 2 delta issues
- ### 0 fixed issues', text='## Total Issue Statistics:
* Error: 0
* High: 1
* Normal: 0
* Low: 1
## New Issue Statistics:
* Error: 0
* High: 1
* Normal: 0
* Low: 1
## Delta Issue Statistics:
* Error: 0
* High: 1
* Normal: 0
* Low: 1
', annotations=[ChecksAnnotation{path='src/main/java/edu/hm/hafner/util/PathUtil.java', startLine=127, endLine=130, annotationLevel=WARNING, message='HIGH:
base must be non-null but is marked as nullable', startColumn=0, endColumn=0, title='NP_PARAMETER_MUST_BE_NONNULL_BUT_MARKED_AS_NULLABLE', rawDetails='<p> This parameter is always used in a way that requires it to be non-null, but the parameter is explicitly annotated as being Nullable. Either the use of the parameter or the annotation is wrong. </p>'}, ChecksAnnotation{path='src/main/java/edu/hm/hafner/util/StringContainsUtils.java', startLine=60, endLine=60, annotationLevel=WARNING, message='LOW:
Comparison of String parameter using == or != in edu.hm.hafner.util.StringContainsUtils.issuesHere(float, float, float, String, String, float, float, float, float, float, float, float)', startColumn=0, endColumn=0, title='ES_COMPARING_PARAMETER_STRING_WITH_EQ', rawDetails='<p>This code compares a <code>java.lang.String</code> parameter for reference equality using the == or != operators. Requiring callers to pass only String constants or interned strings to a method is unnecessarily fragile, and rarely leads to measurable performance gains. Consider using the <code>equals(Object)</code> method instead.</p>'}], images=[]}, actions=[]}
```

**Comment by XiongKezhi** [comment]
it seems the problem is `startLine=127, endLine=130` and `startColumn=0, endColumn=0`.

The start line is different from end line while start column and end column are the provided (although as 0).

We may need more strong validation: when start line and end line are not the same, remove the column field

**Comment by XiongKezhi** [comment]
Instead of being careful in consumers when constructing annotations, maybe we should also check this issue and when it happens, arise an exception early before sending it to GitHub?

**Comment by timja** [comment]
possibly but github could also change that, I think we should have better error reporting when it happens.

**Comment by XiongKezhi** [comment]
Logged the checks parameters when exceptions happen
